### PR TITLE
requirements.txt: Added cloudshell-pdu-raritan

### PR DESCRIPTION
**Pull request by cinlyooi-intel**
Without it you cannot start ttbd server

Signed-off-by: Ooi, Cinly <cinlyooi@intel.com>

### CODE REVIEW

**Comment by inakypg** [comment]
Not sure this is the same one; the raritan pacakge we need is https://help.raritan.com/json-rpc/emx/v3.4.0 and the server will start without it; it will just complain it is there.
THat package is too big though, at some point we have to change the raritan EMX driver to just issue JSON RPC calls.

**Comment by cinlyooi-intel** [comment]
It is not starting for me without raritan. Figuring out that I didn't need it I actually removed the configuration file containing it. Was not sure how long can I continue doing it. Issue is with "import raritan"

**Comment by cinlyooi-intel** [comment]
@inakypg : Can you check out  pdu-json-rpc-sdk-030500-45371/pdu-python-api/
in http://cdn.raritan.com/download/px3/version-3.5.0/PDU_JSON_RPC_SDK_3.5.0_45371.zip. Got the link to the page from Raritan Support. They point me to https://www.raritan.com/support/product/px3

**Comment by inaky-intc** [comment]
implemented in another change

**Pull request closed without merging**
